// web/src/routes/[project]/CurrentDate.svelte
<script lang="ts">
  import { DateTime } from 'luxon';
  import MdKeyboardArrowLeft from 'svelte-icons/md/MdKeyboardArrowLeft.svelte';
  import MdKeyboardArrowRight from 'svelte-icons/md/MdKeyboardArrowRight.svelte';
  import { projectStore } from './stores.svelte';

  let prevStartDate = $derived(
    DateTime.fromISO(projectStore.project.startDate).minus({ months: 1 }).startOf('month').toISO()!
  );
  let prevEndDate = $derived(
    DateTime.fromISO(projectStore.project.startDate).minus({ months: 1 }).endOf('month').toISO()!
  );
  let nextStartDate = $derived(
    DateTime.fromISO(projectStore.project.endDate).plus({ months: 1 }).startOf('month').toISO()!
  );
  let nextEndDate = $derived(
    DateTime.fromISO(projectStore.project.endDate).plus({ months: 1 }).endOf('month').toISO()!
  );
</script>

<div
  class="
    mb-12 mt-10 flex w-full
    md:flex-row
    print:flex-row
    screen:justify-between
  "
>
  <div class="w-1/2">
    <div class="flex flex-row items-center justify-start">
      <a
        class="
          h-14 w-24 text-sky-400
          hover:text-sky-500
          print:hidden
        "
        href={`?startDate=${encodeURIComponent(prevStartDate)}&endDate=${encodeURIComponent(prevEndDate)}`}
      >
        <MdKeyboardArrowLeft size="20" />
      </a>
      <h1
        class="
          font-bold
          md:text-xl
          print:text-2xl
        "
      >
        {DateTime.fromISO(projectStore.project.startDate).toLocaleString(DateTime.DATE_FULL)}
      </h1>
    </div>
  </div>

  <div class="screen:hidden">~</div>

  <div class="w-1/2">
    <div class="flex flex-row items-center justify-end">
      <h1
        class="
          font-bold
          md:text-xl
          print:text-2xl
        "
      >
        {DateTime.fromISO(projectStore.project.endDate).toLocaleString(DateTime.DATE_FULL)}
      </h1>
      <a
        class="
          h-14 w-24 text-sky-400
          hover:text-sky-500
          print:hidden
        "
        href={`?startDate=${encodeURIComponent(nextStartDate)}&endDate=${encodeURIComponent(nextEndDate)}`}
      >
        <MdKeyboardArrowRight />
      </a>
    </div>
  </div>
</div>

// web/components/CurrentDate.tsx
import { observer } from "mobx-react";
import Link from "next/link";
import * as React from "react";
import { RootStoreContext } from "../stores/rootStore";
import { DateTime } from "luxon";

import { MdKeyboardArrowLeft, MdKeyboardArrowRight } from "react-icons/md";

export const CurrentDate: React.FC<{ className: string }> = observer(
  ({ className }) => {
    const { uiStore, projectStore } = React.useContext(RootStoreContext);

    return (
      <>
        <div
          className={`flex flex-col md:flex-row print:flex-row w-full ${className}`}
        >
          <div className="w-full md:w-1/2">
            <div className="flex flex-row items-center justify-start">
              <Link
                href={{
                  pathname: `/${projectStore.currentProject.name}`,
                  query: {
                    startDate: DateTime.fromISO(
                      uiStore.selectedPeriod.startDate
                    )
                      .minus(1, "month")
                      .startOf("month")
                      .toISO(),
                    endDate: DateTime.fromISO(uiStore.selectedPeriod.startDate)
                      .minus(1, "month")
                      .endOf("month")
                      .toISO(),
                  },
                }}
              >
                <a>
                  <MdKeyboardArrowLeft
                    size={70}
                    className="text-sky-500 print:hidden"
                  />
                </a>
              </Link>
              <h1 className="print:text-3xl screen:text-4xl md:text-5xl font-bold">
                {DateTime.fromISO(
                  uiStore.selectedPeriod.startDate
                ).toLocaleString(DateTime.DATE_FULL)}
              </h1>
            </div>
          </div>
          <div className="w-full md:w-1/2">
            <div className="flex flex-row items-center justify-end">
              <h1 className="print:text-3xl screen:text-4xl md:text-5xl font-bold">
                {DateTime.fromISO(
                  uiStore.selectedPeriod.endDate
                ).toLocaleString(DateTime.DATE_FULL)}
              </h1>
              <Link
                href={{
                  pathname: `/${projectStore.currentProject.name}`,
                  query: {
                    startDate: DateTime.fromISO(uiStore.selectedPeriod.endDate)
                      .plus(1, "month")
                      .startOf("month")
                      .toISO(),
                    endDate: DateTime.fromISO(uiStore.selectedPeriod.endDate)
                      .plus(1, "month")
                      .endOf("month")
                      .toISO(),
                  },
                }}
              >
                <a>
                  <MdKeyboardArrowRight
                    size={70}
                    className="text-sky-500 print:hidden"
                  />
                </a>
              </Link>
            </div>
          </div>
        </div>
      </>
    );
  }
);
